# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  0 19 * * *
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{secrets.PAT_TOKEN}}

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
  
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.3.0
      
  
    - name: crawling and push
      run: |
        pip install beautifulsoup4 requests pytz
        python daedeok.py
        git add meal.txt
        git commit -m "update"
        git push origin master
